### ISSUE TITLE
An error occurred while loading view: autodev.autodevGUIView

### ISSUE THREAD

**Issue by maximedupre** [unit-mesh/auto-dev-vscode#16]
Simply installed the extension and when I open the AutoDev tab, this is the error I get:

> An error occurred while loading view: autodev.autodevGUIView

(Same after restarting VSC)

**Comment by phodal** [comment]
The GUI feature is still under development by @CGQAQ .

**Comment by maximedupre** [comment]
@phodal Got it. So is there a CLI that comes with installing the extension? Can you kindly point me to the doc that describes how to use AutoDev? Can't find it on this repo or the JetBrains one :/

**Comment by maximedupre** [comment]
> For use AutoDev, you can follow https://ide.unitmesh.cc/ to use it.

So AutoDev currently only works as a JetBrains plugin?

**Comment by phodal** [comment]
@maximedupre VSCode version is working in progress. For now, you can just upgrade the VSCode version, will see the AutoDev webview which based on Continue.dev

**Comment by maximedupre** [comment]
@phodal Ok I see. Thanks for the answer.

I guess what I'm asking is: "Is AutoDev only available as an IDE extension?"

There is no "standalone"/CLI version of AutoDev?

**Comment by phodal** [comment]
No, because the IDE/editor can provide more toolchain ecosystem , which will make better prompt's context.
