### ISSUE TITLE
VSCode 有配置AutoDev插件的说明文档吗？

### ISSUE THREAD

**Issue by liuq29** [unit-mesh/auto-dev-vscode#17]
大佬，
     VSCode安装好AutoDev插件之后不知道怎么配置settings.json文件，请问有文档说明吗？

**Comment by zhengxs2018** [comment]
可以试试在 settings 中搜索 autodev

<img width="1101" alt="image" src="https://github.com/unit-mesh/auto-dev-vscode/assets/7506913/73ef5f8d-9e19-47bc-89a7-53c388daa935">

然后配置你的 apikey

<img width="441" alt="image" src="https://github.com/unit-mesh/auto-dev-vscode/assets/7506913/971d6ecc-b846-419a-9740-4bbef05bd6ab">

**Comment by chatterzhao** [comment]
<img width="699" alt="image" src="https://github.com/unit-mesh/auto-dev-vscode/assets/11829944/de272d32-35a1-4ed6-8bbf-1a683adaf8f2">
