### ISSUE TITLE
扩展拖了在右侧显示，关闭扩展后无法重新显示

### ISSUE THREAD

**Issue by chatterzhao** [unit-mesh/auto-dev-vscode#20]
版本: 1.88.1
提交: e170252f762678dec6ca2cc69aba1570769a5d39
日期: 2024-04-10T17:43:08.196Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

以上是我的vscode环境。
1.将左侧活动栏的扩展，拖了在右侧显示。
2.点击右侧显示扩展右上角的x
3.这个时候，在代码上右键，选择任何一个选项都无法让扩展再次显示
4.重启vscode后，选择代码，右键，也仅有“解释此代码”可以让扩展显示。其他选项都不可触发显示。

**Comment by phodal** [comment]
右侧菜单的其它选项的功能还没实现……
