### ISSUE TITLE
内网使用自定义部署模型

### ISSUE THREAD

**Issue by tanfer** [unit-mesh/auto-dev-vscode#29]
### Validations

- [ ] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

在内网环境配置了自定义部署的模型，没有成功，是我的打开方式不对嘛

**Comment by phodal** [comment]
不确定，现在还不是正式版，建议你自己  debug 一下

**Comment by zhengxs2018** [comment]
你这么配置的？

**Comment by phodal** [comment]
参考：https://github.com/unit-mesh/auto-dev-vscode/tree/master/examples/ollama-chat-server
