### ISSUE TITLE
几个小bug

### ISSUE THREAD

**Issue by anrgct** [unit-mesh/auto-dev-vscode#44]
### Before submitting your bug report

- [ ] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Relevant environment info

```Markdown
- OS: macos 12.7.5
- AutoDev VSCode: v0.3.1
- IDE: vscode 1.89.1 (Universal）
```

### Description

1. 无法使用中文提示词，vscode display lang已经设置了中文
2. 修改了setting中预设的模型，右键“解释此代码”，显示“暂不支持此模型使用”，并且提示“Failed to find chat model configuration for undefined”，但是点击对话框右下角的“enter”又可以触发对话。
3. 通过“Natural language search (Hyde Code strategy)”触发的对话，有时会显示在左边对话框，普通聊天模式出现，有时又会在终端栏的输出日志中，日志模式出现。

**Comment by phodal** [comment]
问题  1，能再展示一些吗，看不到复现的步骤

@zhengxs2018 问题 2  这个有空的时候看看？

问题  3，日志相关的只是用来辅助，最后都会放到聊天模式中。

**Comment by anrgct** [comment]
1 bug我是通过右键菜单的“解释此代码”、“修复此代码”调出的，它们的prompt都是英文

**Comment by phodal** [comment]
哦，懂了，这几个地方还没进行国际化。 @zhengxs2018 问题  2  我修好了，应该是 binding  的问题

**Comment by phodal** [comment]
@anrgct 可以从这里下载新版本，测试：https://github.com/unit-mesh/auto-dev-vscode/actions/runs/9232700364

**Comment by anrgct** [comment]
实事：测试包费劲安装后无法加载，左侧面板进度条滚动，右键菜单没有添加
假话：我很喜欢这个项目，很在意这个bug，请尽快修复，我会免费测试验证的
真话：产品完成度低，bug多，弃坑，男明星轧戏没意思

**Comment by phodal** [comment]
哈哈哈，感谢吐槽。毕竟是个开源项目，而且还没有  1.0……

**Comment by anrgct** [comment]
老铁，建议精力有限就把核心功能抓紧抓牢，不要广撒网啦

**Comment by phodal** [comment]
大概率是流水线构建出来的版本有问题

**Comment by phodal** [comment]
新版本已经发布：https://marketplace.visualstudio.com/items?itemName=Phodal.autodev

**Comment by anrgct** [comment]
![1716727639626](https://github.com/unit-mesh/auto-dev-vscode/assets/16172523/005d058c-aa07-43b7-a698-2810257751e9)
我都不好意思说重话了😰

**Comment by zhengxs2018** [comment]
> ![1716727639626](https://private-user-images.githubusercontent.com/16172523/333879780-005d058c-aa07-43b7-a698-2810257751e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NzIwNjIsIm5iZiI6MTcxNjc3MTc2MiwicGF0aCI6Ii8xNjE3MjUyMy8zMzM4Nzk3ODAtMDA1ZDA1OGMtYWEwNy00M2I3LWE2OTgtMjgxMDI1Nzc1MWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDAxMDI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMmU5ZTI0NWJjM2JmYTIxMTZlMTEwMGU4ZDg5NWM1M2NkNzg5MjVhYTU3Y2U3ODliNDg4MDhkNzUxODI3ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._uXN8rfrzcYjjm0m2WczoZXg5L-GrwsKSYHX98o_07o) 我都不好意思说重话了😰

这是 continue 的 BUG，代码已经发过去了，但 gui 那边，调用后还是旧的，应该和它内部处理机制有关。。。

我们这边没有 react 方面的专家，如果你懂 react ，欢迎一起来贡献！

**Comment by phodal** [comment]
我们是靠兴趣发电的开源项目，欢迎来新 issue @anrgct
