### ISSUE TITLE
The `temperature` settings not work

### ISSUE THREAD

**Issue by LeoLiuYan** [unit-mesh/auto-dev-vscode#65]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Relevant environment info

```Markdown
- OS: macOS 14.1
- AutoDev VSCode: v0.5.0
- IDE: VSCode 1.91.0 (Universal)
```

### Description

When set the `temperature` parameter in `settings.json`,  and restart the VSCode. But when using autoCompletion,  the real value of `temperature` is not changed.

The VSCode settings:
![image](https://github.com/unit-mesh/auto-dev-vscode/assets/5344039/f8922457-150d-4ea5-84d4-d8ea105f4896)

The real value captured in LLM Server:
![image](https://github.com/unit-mesh/auto-dev-vscode/assets/5344039/51a5ed68-6717-4de8-8b30-610d85a8b0ee)

### To reproduce

1. Change the value of `temperature` in `settings.json` file
2. Restart the IDE
3. Capturing the network packages in LLM Server
4. Use autoCompletion

**Comment by meteor199** [comment]
```

{
	"autodev.completions.parameters": {
		"temperature": 0,
		"top_p": 0.9,
		"max_tokens": 500
	}
}
```
这样试下呢

**Comment by zhengxs2018** [comment]
@meteor199 `autodev.chat.models` 是 webview 下方的模型列表，不是代码补全或内部生成的配置。

**发送配置到 webview**

webview 启动时，会发送 `config/getBrowserSerialized` 事件，然后通过 `listModels` 获取配置的 json 模型并发送过去。

- [config/getBrowserSerialized](https://github.com/unit-mesh/auto-dev-vscode/blob/053680aafe9920c1f94db755b45cd0af538d8495/src/editor/views/chat/continue/continueViewProvider.ts#L167)
- [listModels](https://github.com/unit-mesh/auto-dev-vscode/blob/053680aafe9920c1f94db755b45cd0af538d8495/src/editor/views/chat/continue/continueViewProvider.ts#L268)

**webview 发送对话请求到编辑器**

webview 发送 `llm/streamChat` 事件，传递的参数大概是：

```jsonc
{
   "title": "配置的 chat 模型的 title",
   "completionOptions": {}, // 对话配置
   "messages": [] // 消息列表
}
```

我用 title 去 `autodev.chat.models` 匹配，获得真正的模型名称，然后调用 `LanguageModelService`。

<img width="661" alt="image" src="https://github.com/user-attachments/assets/d7acae54-b733-4174-962c-0e7eb5863bff">

我把 `autodev.chat.models` 上的参数和 `completionOptions` 的参数都丢过去了，但用的浅合并。


问题应该出现在浅合并上，可能哪里有 `temperature` 属性？`我还没去检查`。


后续的逻辑中，参数时一直在透传的：

<img width="1490" alt="image" src="https://github.com/user-attachments/assets/522a79fc-e6c9-4f5c-aa23-0010883166a7">

最近忙公司项目，偷懒没去查，你们要是有空，可以按我的提示去试试改。。。
