### ISSUE TITLE
Generate Comment doesn't work

### ISSUE THREAD

**Issue by WeijianXu** [unit-mesh/auto-dev-vscode#71]
### Before submitting your bug report

- [x] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [x] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Relevant environment info

```Markdown
- OS: window 11
- AutoDev VSCode: v0.5.2
- IDE:
```

### Description

After Selected code, then click right contextmenu autodev->Generate Comment. It doesn't work. In the output panel, it shows "[error] Commands error 0"

### To reproduce

1.  Selected code;
2. Click right contextmenu autodev->Generate Comment;
3. See error: In the output panel, it shows "[error] Commands error 0"

![d33700c329c87751f2a7bce9909da64](https://github.com/user-attachments/assets/4a64eb4b-14b6-4cbc-9d25-01f949189793)

![6378c0d9acc9712acccb0b8f4abed67](https://github.com/user-attachments/assets/2441d979-bd01-4021-969b-2522af427030)

**Comment by zhengxs2018** [comment]
用的哪家的模型？

**Comment by phodal** [comment]
使用的是什么语言？

**Comment by chenqf** [comment]
我这边遇到同样的问题， 是用的模型是 Tongyi

**Comment by phodal** [comment]
可能得看看日志；

<img width="1037" alt="图片" src="https://github.com/user-attachments/assets/1ee2f88c-f30e-4c92-8398-40d4a937c7f0">
