### ISSUE TITLE
建议增加一个新模板标记符号

### ISSUE THREAD

**Issue by a793181018** [unit-mesh/auto-dev-vscode#77]
### Validations

- [ ] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

建议增加一个新模板标记符号，用于用户自定义设定框架上下文文件组，以提高推理的精度

**Comment by phodal** [comment]
欢迎来 PR，详细逻辑见：

https://github.com/unit-mesh/auto-dev-vscode/blob/f73a13fbb69d51190330941a71932257566a7ec9/src/editor/editor-api/QuickAction.ts#L56-L70

https://github.com/unit-mesh/auto-dev-vscode/blob/f73a13fbb69d51190330941a71932257566a7ec9/src/prompt-manage/custom-action/CustomActionExecutor.ts#L20-L30
