### ISSUE TITLE
autodev有实现统计代码补全接受度的功能呢？

### ISSUE THREAD

**Issue by keezen** [unit-mesh/auto-dev-vscode#84]
### Validations

- [X] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

类似：https://github.com/github-copilot-resources/copilot-metrics-viewer

**Comment by phodal** [comment]
没有
