### ISSUE TITLE
希望增加一个给类代码块的解析模块

### ISSUE THREAD

**Issue by a793181018** [unit-mesh/auto-dev-vscode#88]
### Validations

- [ ] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) that requests the same enhancement

### Problem

目前缺少一个能够对类代码块解析的模块，对模块有以下需求
1.解析类的成员变量，获得成员变量名、成员变量注释、成员变量类型.
2.解析类的成员方法，获得成员方法名称、成员方法注释、成员方法参数（参数的类型、参数的名称、参数的说明）、返回值（返回值类型，返回值说明）

### Solution

想要获得通过在类代码节点上添加一个codelens按钮实现当前类的解析

**Comment by phodal** [comment]
已经有了

<img width="704" alt="图片" src="https://github.com/user-attachments/assets/85e01622-232b-487a-8b2a-05f6f5d20b4f">
