### ISSUE TITLE
vscode 如何配置本地服务器上的模型？

### ISSUE THREAD

**Issue by wukongbuku** [unit-mesh/auto-dev-vscode#90]
### Before submitting your bug report

- [ ] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Description

类似于这样的格式，pycharm就可以配置成功，但是vscode就不行

有没有本地配置的参考文档，参考一下

(https://github.com/user-attachments/assets/4963104c-a889-4474-99de-381426192c59)

**Comment by zhengxs2018** [comment]
**vscode 版没有做自定义格式支持。**

如果你的本地服务支持响应 openai 的兼容格式，可以通过 openai 的 provider 进行使用，如果不支持，需要自己本地转换下。

可以看 `examples/ollama-chat-server` 的代码，就是将 ollama 的响应转为 openai 的兼容格式:

PS: ollama 自身就支持 openai 的兼容调用
