### ISSUE TITLE
RAG使用教程

### ISSUE THREAD

**Issue by keezen** [unit-mesh/auto-dev-vscode#91]
### Before submitting your bug report

- [ ] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Relevant environment info

```Markdown
OS: e.g. windows 11
AutoDev VSCode: e.g. v0.5.2
IDE: e.g. VSCode 1.94.0
```

### Description

代码补全中想使用整个项目的代码作为上下文，但文档https://vscode.unitmesh.cc/中似乎没有看到rag的配置教程？
求RAG使用指导

**Comment by phodal** [comment]
暂时不支持
