### ISSUE TITLE
模型返回异常

### ISSUE THREAD

**Issue by Rainmen-xia** [unit-mesh/auto-dev-vscode#98]
### Before submitting your bug report

- [X] I'm not able to find an [open issue](https://github.com/unit-mesh/auto-dev-vscode/issues?q=is%3Aopen+is%3Aissue) that reports the same bug
- [ ] I've seen the [troubleshooting guide](https://vscode.unitmesh.cc/troubleshooting) on the AutoDev Docs

### Relevant environment info

```Markdown
- OS:macos
- AutoDev VSCode:0.5.2
- IDE:Version: 1.96.0-insider (Universal)
```

### Description

看图：
![image](https://github.com/user-attachments/assets/8a40fe56-234a-489b-9af1-05cc58c7a6b2)

### To reproduce

1、安装0.5.2
2、配置openai的key之后输入“你好”
返回：Error: 400 Unrecognized request argument supplied: title

**Comment by zhengxs2018** [comment]
#99
